### ISSUE TITLE
Standard procedure in GUI for finding Python runtime

### ISSUE THREAD

**Issue by NathanChiu** [retallickj/siqad#18]
Consider utilisation of Robert's Powershell scripts

**Comment by samuelngsh** [comment]
There is now a rather hacky way where SiQAD steps through [/resources/python_paths.xml](../blob/master/resources/python_paths.xml) to find a workable Python interpreter. The user may override this via the settings dialog by entering the absolute path to a Python interpreter of their own choice.

A less hacky implementation with a GUI frontend has been planned, please refer to #39.
